### ISSUE TITLE
encoded files?

### ISSUE THREAD

**Issue by catsmoker** [oop7/IDM-Activator#1]
[encoded.txt](https://github.com/user-attachments/files/17651804/encoded.txt)
[encoded_2.txt](https://github.com/user-attachments/files/17651805/encoded_2.txt)
[encoded_3.txt](https://github.com/user-attachments/files/17651806/encoded_3.txt)

**Comment by oop7** [comment]
1. **encoded.txt** — Contains a cracked version of `IDM.exe`
2. **encoded_2.txt** — Holds the necessary registry values to activate IDM.
3. **encoded_3.txt** — Contains registry entries to add additional file extensions to IDM's download options.

You can view how these files are used within `script.bat`, which outlines the decoding process and shows how each file is exported and applied during installation.
