### ISSUE TITLE
virus detect

### ISSUE THREAD

**Issue by hexada-tech** [oop7/IDM-Activator#2]
Detection ID: SuspiciousBehavior.91FED16900136168

**Comment by oop7** [comment]
This is the result from VirusTotal: [0/73 detections](https://www.virustotal.com/gui/file/3d7bc8fcc9b259e1363dedb1da696d675b868b55e312b917420a421088f53e12), no virus. Ensure the MD5 of the file matches.

**Comment by Kirakula** [comment]
The checked zip file is not infected, you are right about that. But the script, bat file is available when the zip file is unpacked.
![2024-11-19 222924](https://github.com/user-attachments/assets/4f46b7cc-8023-42b9-b588-1a576825cd94)

https://www.virustotal.com/gui/file/9524ad378ed592f9e364e81523684e625685d56ba336c274b50fe92dd3c927c9

This terminal command is also interrupted by all antivirus programs with a virus alert.
irm https://github.com/oop7/IDM-Activator/releases/download/v1.5/v1.5.zip -OutFile v1.5.zip; Expand-Archive v1.5.zip -DestinationPath . -Force; cmd.exe /c .\v1.5\script.bat

Thank you for your help to AliDbg, I'm not surprised, because his patch is also full of viruses(hímnemű)

**Comment by hexada-tech** [comment]
> The checked zip file is not infected, you are right about that. But the script, bat file is available when the zip file is unpacked.
> ![2024-11-19 222924](https://github.com/user-attachments/assets/4f46b7cc-8023-42b9-b588-1a576825cd94)
> 
> https://www.virustotal.com/gui/file/9524ad378ed592f9e364e81523684e625685d56ba336c274b50fe92dd3c927c9
> 
> This terminal command is also interrupted by all antivirus programs with a virus alert.
> irm https://github.com/oop7/IDM-Activator/releases/download/v1.5/v1.5.zip -OutFile v1.5.zip; Expand-Archive v1.5.zip -DestinationPath . -Force; cmd.exe /c .\v1.5\script.bat
> 
> Thank you for your help to AliDbg, I'm not surprised, because his patch is also full of viruses(hímnemű)
> 
> 

Yes bro he encoded 3 files in src folder I think those files is a virus bro thank God I was abble to find it if not who else know what will happen to my computer

**Comment by Vanic24** [comment]
Not working with latest version. IDM still showing "registered with fake serial........ even after activating".....

**Comment by oop7** [comment]
Thank you for raising your concerns.

Let me clarify a few points:

1. **False Positives:**
    The detection you’ve encountered on VirusTotal (1/63) is a false positive, which can happen with batch scripts or encoded files. These tools are often flagged by antivirus programs due to their automation or modification capabilities, even if they are completely harmless.

2. **Encoded File Explanation:**
    As explained in the README, the encoded file is a required component for the script's functionality. It includes the AliDbg cracked version, which is necessary for this project. However,**Maybe in the future, I will add more cracked versions of IDM from other sources.**

3. **Transparency:**
    This project is fully open-source, and you are encouraged to review the code and verify its safety yourself. There’s nothing hidden or malicious—everything is as stated in the repository.

4. **Disclaimer:**
    Some users may prefer not to use the project due to the nature of the encoded file. That’s completely fine, and I respect your decision. Please note, though, that assumptions based solely on antivirus detections can be misleading.

If you have any specific concerns or questions, feel free to ask. I’m happy to clarify further.

**Comment by oop7** [comment]
> Not working with latest version. IDM still showing "registered with fake serial........ even after activating".....

**Uninstall IDM Completely:**

- Use the official uninstaller or a trusted third-party uninstaller to ensure all files, including registry entries, are removed.
