### ISSUE TITLE
Change license name?

### ISSUE THREAD

**Issue by anburocky3** [oop7/IDM-Activator#3]
我现在就用了。有用。

但是有什么方法可以将许可证名称从 Enjoy<3 修改为我的名字吗？

**Comment by anburocky3** [comment]
Did it yesterday, but it would be cool if we pass the license name in the terminal. It would be cool i guess?

**Comment by oop7** [comment]
Thank you for the suggestion! Allowing the license name to be passed via the terminal does sound like a handy feature that could make the script more user-friendly
